// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pasajes.Api.Entities;

namespace Pasajes.Api.Migrations
{
    [DbContext(typeof(TalesContext))]
    [Migration("20190626192642_PasajesDbInitialMigration")]
    partial class PasajesDbInitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pasajes.Api.Entities.Tale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Century");

                    b.Property<string>("Country");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.ToTable("Tales");
                });

            modelBuilder.Entity("Pasajes.Api.Entities.TaleSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Priority");

                    b.Property<Guid>("TaleId");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("TaleId");

                    b.ToTable("TaleSources");
                });

            modelBuilder.Entity("Pasajes.Api.Entities.TaleSource", b =>
                {
                    b.HasOne("Pasajes.Api.Entities.Tale", "Tale")
                        .WithMany("TaleSources")
                        .HasForeignKey("TaleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
