// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pasajes.Api.Entities;

namespace Pasajes.Api.Migrations
{
    [DbContext(typeof(TalesContext))]
    partial class TalesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pasajes.Api.Entities.Tale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<int>("Century");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int?>("Year");

                    b.HasKey("Id");

                    b.ToTable("Tales");
                });

            modelBuilder.Entity("Pasajes.Api.Entities.TaleLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City")
                        .HasMaxLength(100);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<Guid>("TaleId");

                    b.HasKey("Id");

                    b.HasIndex("TaleId");

                    b.ToTable("TaleLocation");
                });

            modelBuilder.Entity("Pasajes.Api.Entities.TaleSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Priority");

                    b.Property<Guid>("TaleId");

                    b.Property<string>("Url")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("TaleId");

                    b.ToTable("TaleSources");
                });

            modelBuilder.Entity("Pasajes.Api.Entities.TaleLocation", b =>
                {
                    b.HasOne("Pasajes.Api.Entities.Tale", "Tale")
                        .WithMany("TaleLocations")
                        .HasForeignKey("TaleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Pasajes.Api.Entities.TaleSource", b =>
                {
                    b.HasOne("Pasajes.Api.Entities.Tale", "Tale")
                        .WithMany("TaleSources")
                        .HasForeignKey("TaleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
